name: empty_annotation
description: An annotation package for generating empty classes.

version: 0.0.2

homepage: https://github.com/giuseppeps/empty_annotation/tree/main/empty_annotation
repository: https://github.com/giuseppeps/empty_annotation
issue_tracker: https://github.com/giuseppeps/empty_annotation/issues

environment:
  sdk: ^3.5.3

dev_dependencies:
  flutter_lints: ^4.0.0
