name: empty_generator
description: "Code generator for use with the Empty Annotation package."

version: 0.0.1+1

homepage: https://github.com/giuseppeps/empty_annotation/empty_generator
repository: https://github.com/giuseppeps/empty_annotation/empty_generator
issue_tracker: https://github.com/giuseppeps/empty_annotation/empty_generator/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.5.0
  empty_annotation:
    path: ../empty_annotation
  build: ^2.4.1
  source_gen: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  empty_generator:
    path: ../
  flutter_lints: ^4.0.0
