name: empty_generator
description: "Code generator for use with the Empty Annotation package."

version: 0.0.2

homepage: https://github.com/giuseppeps/empty_annotation/tree/main/empty_generator
repository: https://github.com/giuseppeps/empty_annotation
issue_tracker: https://github.com/giuseppeps/empty_annotation/issues

environment:
  sdk: ^3.5.3

dependencies:
  analyzer: ^6.5.0
  empty_annotation: ^0.0.1+1
  build: ^2.4.1
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
